# Use new container infrastructure to enable caching
sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.stack
  - $HOME/.local

matrix:
  include:
  - { env: BUILD=stack RESOLVER=ghc-7.8, compiler: ghc-7.8, language: generic, addons: { apt: { packages: [ libgmp-dev ] } } }
  - { env: BUILD=stack RESOLVER=ghc-8.2, compiler: ghc-8.2, language: generic, addons: { apt: { packages: [ libgmp-dev ] } } }
  - { env: BUILD=stack RESOLVER=ghc-7.10, compiler: ghc-7.10, language: generic, addons: { apt: { packages: [ libgmp-dev ] } } }
  - { env: BUILD=stack RESOLVER=ghc-8.0, compiler: ghc-8.0, language: generic, addons: { apt: { packages: [ libgmp-dev ] } } }
  - { env: BUILD=stack RESOLVER=ghc-8.0, compiler: ghc-8.0, language: generic, addons: { apt: { packages: [ libgmp-dev ] } }, os: osx }
  - { env: BUILD=stack RESOLVER=ghc-8.0-edge, compiler: ghc-8.0-edge, language: generic, addons: { apt: { packages: [ libgmp-dev ] } } }
  - { env: BUILD=stack RESOLVER=ghc-8.0-experimental, compiler: ghc-8.0-experimental, language: generic, addons: { apt: { packages: [ libgmp-dev ] } } }
  - { env: BUILD=hlint, compiler: hlint, language: generic }
  - { env: BUILD=weeder, compiler: weeder, language: generic, addons: { apt: { packages: [ libgmp-dev ] } } }
  allow_failures:
  - { env: BUILD=stack RESOLVER=ghc-8.0-experimental, compiler: ghc-8.0-experimental, language: generic, addons: { apt: { packages: [ libgmp-dev ] } } }
  - { env: BUILD=hlint, compiler: hlint, language: generic }
  - { env: BUILD=weeder, compiler: weeder, language: generic, addons: { apt: { packages: [ libgmp-dev ] } } }

install:
  - export PATH=$HOME/.local/bin::$HOME/.cabal/bin:$PATH
  - mkdir -p ~/.local/bin
  - |
    case "$BUILD" in
      stack|weeder)
        if [ `uname` = "Darwin" ]
        then
          travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
        else
          travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        fi
      ;;
    cabal)
      ;;
    esac

script:
- |
  set -ex
  if [ "x${RUNTEST}" = "xfalse" ]; then exit 0; fi
  case "$BUILD" in
    stack)
      # create the build stack.yaml
      case "$RESOLVER" in
      ghc-7.8)
        echo "{ resolver: lts-2.22, packages: [ '.', basement/ ], extra-deps: [ gauge-0.2.1 ], flags: { foundation: { bounds-check: true, linktest: true } } }" > stack.yaml
        export HADDOCK_OPTs="--no-haddock"
        ;;
      ghc-8.2)
        echo "{ resolver: lts-10.4, packages: [ '.', basement/ ], extra-deps: [ gauge-0.2.1 ], flags: { foundation: { bounds-check: true, linktest: true } } }" > stack.yaml
        export HADDOCK_OPTs="--haddock --no-haddock-deps"
        ;;
      ghc-7.10)
        echo "{ resolver: lts-6.35, packages: [ '.', basement/ ], extra-deps: [ gauge-0.2.1 ], flags: { foundation: { bounds-check: true, linktest: true } } }" > stack.yaml
        export HADDOCK_OPTs="--haddock --no-haddock-deps"
        ;;
      ghc-8.0)
        echo "{ resolver: lts-9.21, packages: [ '.', basement/ ], extra-deps: [ gauge-0.2.1 ], flags: { foundation: { bounds-check: true, linktest: true } } }" > stack.yaml
        export HADDOCK_OPTs="--haddock --no-haddock-deps"
        ;;
      ghc-8.0)
        echo "{ resolver: lts-9.21, packages: [ '.', basement/ ], extra-deps: [ gauge-0.2.1 ], flags: { foundation: { bounds-check: true, linktest: true } } }" > stack.yaml
        export HADDOCK_OPTs="--haddock --no-haddock-deps"
        ;;
      ghc-8.0-edge)
        echo "{ resolver: lts-9.21, packages: [ '.', basement/, edge/ ], extra-deps: [ gauge-0.2.1 ], flags: { foundation: { bounds-check: true, linktest: true } } }" > stack.yaml
        export HADDOCK_OPTs="--haddock --no-haddock-deps"
        ;;
      ghc-8.0-experimental)
        echo "{ resolver: lts-9.21, packages: [ '.', basement/ ], extra-deps: [ gauge-0.2.1 ], flags: { foundation: { bounds-check: true, linktest: true, experimental: true } } }" > stack.yaml
        export HADDOCK_OPTs="--haddock --no-haddock-deps"
        ;;
      esac
      # build & run test
      stack --no-terminal test --install-ghc --coverage --bench --no-run-benchmarks \
          ${HADDOCK_OPTS}
      ;;
    hlint)
      curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s . --cpp-define=__GLASGOW_HASKELL__=800 --cpp-define=x86_64_HOST_ARCH=1 --cpp-define=mingw32_HOST_OS=1
      ;;
    weeder)
      stack --no-terminal build --install-ghc
      curl -sL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s .
      ;;
  esac
  set +ex

